//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.24 at 08:40:18 PM CST 
//


package net.madz.crmp.db.metadata.configuration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatabaseProduct.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DatabaseProduct">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MS Access"/>
 *     &lt;enumeration value="MySQL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DatabaseProduct")
@XmlEnum
public enum DatabaseProduct {

    @XmlEnumValue("MS Access")
    MS_ACCESS("MS Access"),
    @XmlEnumValue("MySQL")
    MY_SQL("MySQL");
    private final String value;

    DatabaseProduct(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DatabaseProduct fromValue(String v) {
        for (DatabaseProduct c: DatabaseProduct.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
