//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.24 at 08:40:18 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://madz.net/datasource", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.madz.crmp.db.metadata.configuration;
