//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.25 at 12:34:23 \u4e0b\u5348 CST 
//


package net.madz.crmp.db.metadata.configuration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sku.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="sku">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MySQL"/>
 *     &lt;enumeration value="MS Access"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "sku")
@XmlEnum
public enum Sku {

    @XmlEnumValue("MySQL")
    MY_SQL("MySQL"),
    @XmlEnumValue("MS Access")
    MS_ACCESS("MS Access");
    private final String value;

    Sku(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Sku fromValue(String v) {
        for (Sku c: Sku.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
