//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.25 at 12:34:23 \u4e0b\u5348 CST 
//


package net.madz.crmp.db.metadata.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sku" use="required" type="{http://madz.net/datasource}sku" />
 *       &lt;attribute name="driverClass" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parserClass" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="generatorClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "sku-conf")
public class SkuConf {

    @XmlAttribute(name = "sku", required = true)
    protected Sku sku;
    @XmlAttribute(name = "driverClass", required = true)
    protected String driverClass;
    @XmlAttribute(name = "parserClass", required = true)
    protected String parserClass;
    @XmlAttribute(name = "generatorClass")
    protected String generatorClass;

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link Sku }
     *     
     */
    public Sku getSku() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sku }
     *     
     */
    public void setSku(Sku value) {
        this.sku = value;
    }

    /**
     * Gets the value of the driverClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverClass() {
        return driverClass;
    }

    /**
     * Sets the value of the driverClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverClass(String value) {
        this.driverClass = value;
    }

    /**
     * Gets the value of the parserClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParserClass() {
        return parserClass;
    }

    /**
     * Sets the value of the parserClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParserClass(String value) {
        this.parserClass = value;
    }

    /**
     * Gets the value of the generatorClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneratorClass() {
        return generatorClass;
    }

    /**
     * Sets the value of the generatorClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneratorClass(String value) {
        this.generatorClass = value;
    }

}
